### ISSUE TITLE
Error: Object has been destroyed

### ISSUE THREAD

**Issue by nickfan** [Licoy/girls-reptile#9]
mac 2.0 zip版解压后无效,dmg版本，采集过程会报错：

```
Uncaught Exception:
Error: Object has been destroyed
    at WebContents.send (/Applications/GirlsReptile.app/Contents/Resources/electron.asar/browser/api/web-contents.js:101:15)
    at /Applications/GirlsReptile.app/Contents/Resources/app.asar/dist/electron/main.js:1:39929
    at /Applications/GirlsReptile.app/Contents/Resources/app.asar/node_modules/electron-download-manager/index.js:254:21
    at DownloadItem.item.on (/Applications/GirlsReptile.app/Contents/Resources/app.asar/node_modules/electron-download-manager/index.js:116:21)
    at emitTwo (events.js:126:13)
    at DownloadItem.emit (events.js:214:7)
```

**Comment by Licoy** [comment]
是不是采集过程中你点了关闭窗口

**Comment by nickfan** [comment]
没有吧，最小化而已，
另外 electron-vue套件的组合有点老了，建议用vue-cli3.0+electron-builder来做。
https://github.com/nklayman/vue-cli-plugin-electron-builder
有现成的集成插件。

**Comment by Licoy** [comment]
好的，之后如果有重大迭代更新可能会采取vue-cli3.0+electron-builder的方式来做，不过回归到主体，这个问题您重启一下看看还有吗？

**Comment by nickfan** [comment]
重启后，不最小化貌似没有，是不是使用的那个DownloadManager组件的问题？

**Comment by Licoy** [comment]
我最小化是没有问题，只是如果在执行任务中如果关闭了会报出此异常

**Comment by mlch911** [comment]
我停止采集，点关闭，也会有这个错误

**Comment by Licoy** [comment]
@mlch911 是因为`electron-download-manager`内的下载任务还没有执行完成就退出导致的异常
